Loadout patch
Neefay/BromA-Framework-A3-Addon pull request #175
Opened 2021-07-12 11:46 UTC by HeroesMaker

loadouts modification on PLA, JGSDF and ANZAC.
Added canadian army.
Added SMAW optics and spotting rounds to cargo selection.

2021-07-19 14:46 UTC, Coryf88 requested changes

2021-07-19 14:46 UTC, Coryf88 commented on loadouts/cargo-list.sqf
> +	case "SMAW":{
Instead add to "at", if specAT is a SMAW, so old missions will also get the items.

2021-07-19 14:46 UTC, Coryf88 commented on loadouts/factions/Canada.sqf
> +    A FUCKING LEAF
Unified military of Canada.

2021-07-19 14:46 UTC, Coryf88 commented on loadouts/factions/Canada.sqf
> +    "BRM_BattleUNITS_"+_camo
`"BRM_BattleUNIT_"`

2021-07-19 14:46 UTC, Coryf88 commented on loadouts/factions/Canada.sqf
> +    _factionVehicles = [
Unindent.

2021-07-19 14:46 UTC, Coryf88 commented on loadouts/factions/Canada.sqf
> +};
Remove erroneous `};`

2021-07-19 14:46 UTC, Coryf88 commented on loadouts/factions/JSDF.sqf
> +    "BRM_BattleUNITS_"+_camo
`"BRM_BattleUNIT_"`

2021-07-19 14:46 UTC, Coryf88 commented on loadouts/factions/anzac.sqf
> +    "BRM_BattleUNITS_"+_camo
`"BRM_BattleUNIT_"`

2021-07-19 14:46 UTC, Coryf88 commented on loadouts/factions/anzac.sqf
> +_commonVEST    = "BRM_Protec_"+_camo"_RFL";
Missing `+` after `_camo`.

2021-07-19 14:46 UTC, Coryf88 commented on loadouts/factions/anzac.sqf
> +_officerVEST   = "BRM_Protec_"+_camo"_SL";
Missing `+` after `_camo`.

2021-07-19 14:46 UTC, Coryf88 commented on loadouts/factions/anzac.sqf
> +_ftlVEST       = "BRM_Protec_"+_camo"_TL";
Missing `+` after `_camo`.

2021-07-19 14:46 UTC, Coryf88 commented on loadouts/factions/anzac.sqf
> +_mgVEST        = "BRM_Protec_"+_camo"_MG";
Missing `+` after `_camo`.

2021-07-19 14:46 UTC, Coryf88 commented on loadouts/factions/anzac.sqf
> +_grenadierVEST = "BRM_Protec_"+_camo"_GL";
Missing `+` after `_camo`.

2021-07-19 14:46 UTC, Coryf88 commented on loadouts/faction-list.sqf
> +    case "CANARMY": {
`CAF` instead?

2021-07-19 15:08 UTC, HeroesMaker reviewed
Made the changes requested, that'll teach me to do things half awake.

2021-07-20 01:06 UTC, Coryf88 approved these changes
👍

I tried out Github's `Allow edits by maintainers` feature.
Also, try to create separate PRs for well, separate changes. 😛

2021-07-20 01:19 UTC, merged